name: Python 3.12 Test 
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - run: echo $PATH
      - run: curl -fsSL https://pixi.sh/install.sh | bash
      - run: source /home/runner/.bash_profile
      - run: echo $PATH