name: Python 3.12 Test 
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://pixi.sh/install.sh | bash
      - run: echo /home/runner/.pixi/bin >> $GITHUB_PATH
      - run: pixi init
      - run: pixi add python=3.12
      - run: pixi add poetry
      - run: pixi run poetry install