name: Python 3.12 Test 
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PATH
      - run: curl -fsSL https://pixi.sh/install.sh | bash
      - run: source ~/.bashrc
      - run: echo $PATH